Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2020-11, with the labels that each got.

#54 DOC: Update Installation instructions in README.md
  README.md
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.py
Labels: documentation

#55 BUG: Fix 2 Bugs In read_region
  tests/test_wsireader.py
  tiatoolbox/dataloader/wsireader.py
Labels: bug

#53 NEW: Fallback To Calculate MPP From Standard TIFF Tags
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/dataloader/wsireader.py
  tiatoolbox/utils/misc.py
Labels: enhancement
