Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2021-05, with the labels that each got.

#61 NEW: Tissue Masking
  docs/usage.rst
  requirements_dev.txt
  tests/test_patch_extraction.py
  tests/test_tissuemask.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/tissuemask.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#115 MAINT: Change the name of stainnorm to stain_norm
  tests/test_stainnorm.py
  tiatoolbox/cli.py
Labels: code readability

#117 HOTFIX: Update model URLs to fix tests
  tests/test_models.py
  tests/test_utils.py
  tiatoolbox/models/classification/pretrained_info.py
  tiatoolbox/utils/misc.py
Labels: bug
