Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2021-11, with the labels that each got.

#173 DEV: Update links for Kather dataset
  tests/models/test_dataset.py
  tiatoolbox/models/dataset/info.py
Labels: refactoring

#181 NEW: Add stainaugment feature for stain augmentation
  docs/usage.rst
  examples/05_example_patchpredictor.ipynb
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.py
  tests/test_stainaugment.py
  tiatoolbox/tools/__init__.py
  tiatoolbox/tools/stainaugment.py
Labels: enhancement

#182 NEW: Zoomify Tile Generation
  docs/usage.rst
  requirements.txt
  tests/test_pyramid.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#155 NEW: Add SlideGraph Construction Method In Tools
  docs/conf.py
  docs/usage.rst
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  tests/test_graph.py
  tiatoolbox/tools/graph.py
  whitelist.txt
Labels: enhancement

#196 [skip travis] DEV: Add XML Coverage Report Output to Makefile Recipe
  Makefile
Labels: dev tools

#201 [skip travis] DEV: Increase Cognitive Complexity Limit In setup
  setup.cfg
Labels: dev tools
