Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2021-10, with the labels that each got.

#153 DEV: Re-Organise Loading of Bundled Resources & Remote Samples
  .deepsource.toml
  MANIFEST.in
  data/target_image.png
  requirements.dev.conda.yml
  tests/conftest.py
  tests/test_models.py
  tests/test_patch_extraction.py
  tests/test_save_tiles.py
  tests/test_slide_info.py
  tests/test_stainnorm.py
  tests/test_tissuemask.py
  tests/test_utils.py
  tests/test_visualization.py
  tests/test_wsimeta.py
  tests/test_wsireader.py
  tiatoolbox/data/__init__.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/data/target_image.png
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/utils/image.py
  whitelist.txt
Labels: enhancement, code readability

#128 NEW: Add Model Semantic Segmentation
  .gitignore
  requirements.dev.conda.yml
  requirements.txt
  requirements_dev.txt
  setup.py
  tests/conftest.py
  tests/models/test_abc.py
  tests/models/test_arch_unet.py
  tests/models/test_arch_utils.py
  tests/models/test_arch_vanilla.py
  tests/models/test_dataset.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_data.py
  tests/test_visualization.py
  tests/test_wsireader.py
  tiatoolbox/__init__.py
  tiatoolbox/cli.py
  tiatoolbox/data/__init__.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/models/__init__.py
  tiatoolbox/models/abc.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/backbone/__init__.py
  tiatoolbox/models/classification/__init__.py
  tiatoolbox/models/controller/__init__.py
  tiatoolbox/models/controller/patch_predictor.py
  tiatoolbox/models/controller/semantic_segmentor.py
  tiatoolbox/models/dataset/info.py
  tiatoolbox/utils/misc.py
  tox.ini
Labels: enhancement

#160 BUG: Fix ioconfig bug for semantic segmentation `tile` mode
  tests/models/test_semantic_segmentation.py
  tiatoolbox/models/controller/semantic_segmentor.py
Labels: bug
