Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2021-12, with the labels that each got.

#179 NEW: Add Feature HoVerNet+ model
  tests/models/test_hovernet_plus.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernet_plus.py
Labels: enhancement

#180 EG: SlideGraph Pipeline As Advance Example Usage
  examples/full-pipelines/slide-graph.ipynb
  examples/inference-pipelines/slide-graph.ipynb
Labels: documentation

#212 NEW: Add Simple Zoomify Viewer For WSIReader
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  tests/test_tileserver.py
  tiatoolbox/data/visualization/static/css/fontawesome-all.min.css
  tiatoolbox/data/visualization/static/css/ol-ext.min.css
  tiatoolbox/data/visualization/static/css/ol.css
  tiatoolbox/data/visualization/static/js/ol-ext.min.js
  tiatoolbox/data/visualization/static/js/ol.js
  tiatoolbox/data/visualization/static/js/polyfill.min.js
  tiatoolbox/data/visualization/static/webfonts/fa-brands-400.eot
  tiatoolbox/data/visualization/static/webfonts/fa-brands-400.svg
  tiatoolbox/data/visualization/static/webfonts/fa-brands-400.ttf
  tiatoolbox/data/visualization/static/webfonts/fa-brands-400.woff
  tiatoolbox/data/visualization/static/webfonts/fa-brands-400.woff2
  tiatoolbox/data/visualization/static/webfonts/fa-regular-400.eot
  tiatoolbox/data/visualization/static/webfonts/fa-regular-400.svg
  tiatoolbox/data/visualization/static/webfonts/fa-regular-400.ttf
  tiatoolbox/data/visualization/static/webfonts/fa-regular-400.woff
  tiatoolbox/data/visualization/static/webfonts/fa-regular-400.woff2
  tiatoolbox/data/visualization/static/webfonts/fa-solid-900.eot
  tiatoolbox/data/visualization/static/webfonts/fa-solid-900.svg
  tiatoolbox/data/visualization/static/webfonts/fa-solid-900.ttf
  tiatoolbox/data/visualization/static/webfonts/fa-solid-900.woff
  tiatoolbox/data/visualization/static/webfonts/fa-solid-900.woff2
  tiatoolbox/data/visualization/templates/index.html
  tiatoolbox/visualization/__init__.py
  tiatoolbox/visualization/tileserver.py
Labels: enhancement

#189 EG: Notebook For Prediction Of Molecular Pathways & Key Mutations
  examples/inference-pipelines/idars.ipynb
Labels: documentation

#220 BUG: Fix CLI For Slide-Thumbnail To Save File
  tests/test_slide_info.py
  tests/test_slide_thumbnail.py
  tests/test_wsireader.py
  tiatoolbox/cli/slide_info.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/utils/misc.py
Labels: bug

#223 BUG: Remove ujson From Annotation Store
  tiatoolbox/annotation/storage.py
Labels: bug

#224 ENH: Rename 'boundary' Column To 'geometry' & Rename Variables
  tiatoolbox/annotation/storage.py
Labels: refactoring

#221 STY: Tidy wsireader.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: code readability, refactoring

#225 NEW: Add PCam Patch Classification Models
  tests/conftest.py
  tests/models/test_patch_predictor.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/dataset/classification.py
Labels: enhancement

#207 Notebook For ER Prediction Using SlideGraph Pipeline
  examples/full-pipelines/slide-graph.ipynb
  examples/inference-pipelines/slide-graph.ipynb
Labels: documentation

#206 NEW: Add Basic Feature Detection Mechanisms
  .coveragerc
  pyproject.toml
  tiatoolbox/utils/env_detection.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: enhancement

#222 ENH: On Demand Imports
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#228 [skip travis] DOC: Add Citation
  CITATION.cff
  setup.cfg
Labels: documentation

#209 NEW: Easy Way To Specify / Override MPP & Power For `init` And `open`
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/utils/env_detection.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#217 ENH: Improve Mask-Based Patch Extraction Speed & Add Units Conversion
  tests/test_patch_extraction.py
  tests/test_wsireader.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement
