Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2021-06, with the labels that each got.

#122 DOC: Fix examples in module docstring
  tiatoolbox/utils/transforms.py
  tiatoolbox/wsicore/slide_info.py
  tiatoolbox/wsicore/wsireader.py
Labels: documentation

#120 ENH: Add functionality to read through mask in `patchextraction`
  tests/test_patch_extraction.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#129 DEP: Remove files from `tests/data`
  tests/conftest.py
  tests/data/TCGA-HE-7130-01Z-00-DX1.png
  tests/data/norm_macenko.png
  tests/data/norm_reinhard.png
  tests/data/norm_ruifrok.png
  tests/data/norm_vahadane.png
  tests/data/sample_patch_extraction-noheader.csv
  tests/data/sample_patch_extraction.csv
  tests/data/sample_patch_extraction.json
  tests/data/sample_patch_extraction.npy
  tests/data/sample_patch_extraction_2col.json
  tests/data/sample_patch_extraction_2col.npy
  tests/data/sample_patch_extraction_jp2.csv
  tests/data/sample_patch_extraction_jp2read.npy
  tests/data/sample_patch_extraction_read.npy
  tests/data/sample_patch_extraction_svs.csv
  tests/data/sample_patch_extraction_svs_header.csv
  tests/data/sample_patch_extraction_svsread.npy
  tests/data/source_image.png
  tests/test_utils.py
  tests/test_wsireader.py
Labels: bug, code readability
