Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-03, with the labels that each got.

#307 DEV: Improve CLI
  setup.py
  tests/models/test_patch_predictor.py
  tests/test_slide_info.py
  tests/test_slide_thumbnail.py
  tests/test_stainnorm.py
  tests/test_tiatoolbox.py
  tests/test_tissuemask.py
  tests/test_wsireader.py
  tiatoolbox/cli/__init__.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/read_bounds.py
  tiatoolbox/cli/save_tiles.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/cli/slide_info.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/cli/stain_norm.py
  tiatoolbox/cli/tissue_mask.py
  tiatoolbox/utils/misc.py
  tiatoolbox/wsicore/slide_info.py
Labels: enhancement

#310 DOC: Tidy Annotation Docstrings
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
Labels: documentation

#309 DOC: Tidy wsicore Docstrings
  tiatoolbox/wsicore/save_tiles.py
  tiatoolbox/wsicore/slide_info.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: documentation

#315 DOC: Update HoVerNetPlus metrics
  tiatoolbox/models/architecture/hovernetplus.py
Labels: documentation

#311 DOC: Tidy Miscellaneous Docstrings
  tests/test_data.py
  tests/test_init.py
  tests/test_stainaugment.py
  tests/test_stainnorm.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/__init__.py
  tiatoolbox/models/architecture/idars.py
  tiatoolbox/visualization/tileserver.py
Labels: documentation

#319 TST: Make Stain Norm CLI Tests Use Temp Dir
  tests/models/test_arch_micronet.py
  tests/test_stainnorm.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/architecture/micronet.py
Labels: bug

#316 DEV: Fix Makefile Docs Command
  .gitignore
  Makefile
Labels: bug, dev tools

#306 DOC: Tidy Tools Docstrings
  tiatoolbox/tools/graph.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/scale.py
  tiatoolbox/tools/stainaugment.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/tools/tissuemask.py
Labels: documentation
