Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-11, with the labels that each got.

#505 BUG: Fix R505 Flake8 Error
  tiatoolbox/annotation/storage.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug

#507 🗑️ TST: Prevent Fly Tipping
  tests/models/test_patch_predictor.py
Labels: refactoring

#501 MANT: Refactor Parameterized Tests
  tests/conftest.py
  tests/test_annotation_stores.py
  tests/test_dsl.py
  tests/test_graph.py
  tests/test_wsireader.py
Labels: refactoring

#449 NEW: Add NuClick architecture
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/models/architecture/idars.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
Labels: enhancement

#476 ENH: Add Annotation Store Reader
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_wsireader.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#504 🐳 DEV: Publishing Docker Images
  .github/workflows/docker-publish.yml
  docker/3.10/Debian/Dockerfile
  docker/3.10/Ubuntu/Dockerfile
  docker/3.7/Debian/Dockerfile
  docker/3.8/Debian/Dockerfile
  docker/3.9/Debian/Dockerfile
  docker/3.9/Ubuntu/Dockerfile
Labels: dev tools, release

#498 DEV: Update Dependencies
  docs/requirements.txt
  requirements.txt
  requirements_dev.txt
Labels: dependencies
