Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-06, with the labels that each got.

#345 DEV: Fix Flake8 Errors And Typos In `unet.py`
  tiatoolbox/models/architecture/unet.py
Labels: refactoring

#350 DEV: Fix Flake8 Errors and Typos in `architecture/vanilla.py`
  tiatoolbox/models/architecture/vanilla.py
  whitelist.txt
Labels: refactoring

#363 DEV: Fix Flake8 Errors and Typos in `tests_hovernetplus.py`
  tests/models/test_hovernetplus.py
Labels: code readability

#361 DEV: Fix Flake8 Errors and Typos in `tests\test_save_tiles.py`
  tests/test_save_tiles.py
  whitelist.txt
Labels: code readability

#358 BUGFIX: Fixing for Merging Patch Predictor Output
  tiatoolbox/models/engine/patch_predictor.py
Labels: bug

#367 DEV: Fix Flake8 Errors in `tools/pyramid.py`
  tiatoolbox/tools/pyramid.py
Labels: code readability

#368 DEV: Fix Flake8 SC100 Errors
  tests/models/test_patch_predictor.py
  tests/test_stainaugment.py
  tests/test_tissuemask.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/engine/semantic_segmentor.py
  whitelist.txt
Labels: code readability

#373 NEW: Add Python 3.10 Support
  .travis.yml
  CONTRIBUTING.rst
  docs/installation.rst
  pyproject.toml
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.win64.conda.yml
  setup.py
  tox.ini
Labels: dev tools

#371 DEV: Fix PT011 Pytest Raises is Too Broad
  tests/models/test_patch_predictor.py
  tests/test_stainnorm.py
  tests/test_tissuemask.py
Labels: code readability

#369 DEV: Fix Flake8 Errors in `utils/transforms.py`
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
Labels: code readability

#370 DEV: Fix Flake8 Error R504 Unnecessary Variable Assignment Before Return Statement
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/idars.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/stainnorm.py
Labels: code readability

#366 DEV: Fix Flake8 Errors and Typos in `models/dataset/abc`
  tests/models/test_dataset.py
  tests/models/test_patch_predictor.py
  tiatoolbox/models/dataset/abc.py
Labels: code readability

#377 DEV: Fix Flake8 PIE*, C408 and PT* Errors
  tests/models/test_multi_task_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_init.py
  tests/test_tissuemask.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/semantic_segmentor.py
Labels: code readability

#378 DEV: Fix Flake8 `wsireader`
  tests/models/test_dataset.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/wsicore/wsireader.py
Labels: code readability

#381 DEV: Address Flake8 Linter Issues in `visualization.py`
  tiatoolbox/utils/visualization.py
Labels: code readability

#365 DEV: Fix Flake8 Errors and Typos in `models/engine/patchpredictor.py`
  tiatoolbox/models/engine/patch_predictor.py
Labels: code readability

#379 DEV: Fix Flake8 Errors in `semantic_segmentor.py`
  tiatoolbox/models/engine/semantic_segmentor.py
  whitelist.txt
Labels: code readability

#380 DEV: Replace PlattScaler With Sklearn LogisticRegression
  examples/full-pipelines/slide-graph.ipynb
  tests/test_scale.py
  tiatoolbox/tools/scale.py
Labels: code readability

#321 NEW: CLI For TileServer
  tests/test_tileserver.py
  tiatoolbox/cli/__init__.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/tile_server.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/visualization/tileserver.py
  whitelist.txt
Labels: enhancement
