Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-07, with the labels that each got.

#384 BUG: Fix Errors After Torch Upgrade To Version 1.12
  tests/models/test_feature_extractor.py
Labels: bug

#386 DEV: Set Up GitHub Actions Workflow (Build, Test & Release)
  .github/workflows/python-package.yml
  tests/models/test_abc.py
  tests/models/test_arch_micronet.py
  tests/models/test_dataset.py
  tests/models/test_feature_extractor.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_slide_thumbnail.py
  tests/test_tileserver.py
  tests/test_tissuemask.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/cli/read_bounds.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/cli/tissue_mask.py
  tiatoolbox/utils/env_detection.py
Labels: dev tools

#340 NEW: Add Experimental NGFF Support
  .pre-commit-config.yaml
  tests/test_meta_ngff_dataclasses.py
  tests/test_wsireader.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/wsicore/metadata/__init__.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#389 TST: Set Test Number of Workers Based on CPU Count
  tests/models/test_multi_task_segmentor.py
  tests/models/test_semantic_segmentation.py
Labels: enhancement

#390 BUG: Check That An Input Path Actually Exists
  tests/test_wsireader.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: bug

#398 DEV: Add GitHub Action To Perform Conda Solve
  .github/workflows/conda-env-create.yml
  requirements.dev.conda.yml
  requirements.win64.conda.yml
Labels: dev tools

#403 BUG: Fix tileserver CLI Issues
  MANIFEST.in
  setup.py
  tests/test_tileserver.py
  tiatoolbox/cli/__init__.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/show_wsi.py
Labels: bug

#408 DEV: Missing Imports Check (Pre-Commit Hook)
  pre-commit/missing_imports.py
  whitelist.txt
Labels: dev tools

#413 NEW: Dice Metric
  docs/usage.rst
  tests/test_metrics.py
  tiatoolbox/utils/metrics.py
Labels: enhancement

#420 MAINT: Refactor Requirements Consistency
  pre-commit/requirements_consistency.py
Labels: enhancement

#417 DEV: Add Notebook AST Pre-Commit Hook
  .pre-commit-config.yaml
  pre-commit/notebook_check_ast.py
Labels: documentation, dev tools

#330 NEW: Annotation Rendering
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_tileserver.py
  tiatoolbox/annotation/__init__.py
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/cli/show_wsi.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/visualization/tileserver.py
  whitelist.txt
Labels: enhancement

#423 BUG: Fix Issue #410: Update colorbar_params arguments in overlay_prediction_mask function
  tiatoolbox/utils/visualization.py
Labels: bug

#428 ENH: Improve Docstring Validity Test Error Output
  tests/test_docs.py
  tiatoolbox/annotation/storage.py
Labels: documentation, dev tools

#418 DOC: JNB-RTD consistency for 03-tissue-masking.ipynb
  examples/03-tissue-masking.ipynb
Labels: documentation

#430 BUG: Correct error in nucleus instance segmentor engine
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
Labels: bug
