Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-01, with the labels that each got.

#257 BUG: Fix Empty Query in Instance Segmentor
  tests/test_utils.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
Labels: bug

#258 MAINT: Setting Up Conditional Tests Using "pytest skipif"
  tests/models/test_abc.py
  tests/models/test_dataset.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_utils.py
  tiatoolbox/utils/env_detection.py
  whitelist.txt
Labels: bug

#266 BUG: Pixman Version Check
  tests/test_utils.py
  tiatoolbox/utils/__init__.py
  tiatoolbox/utils/env_detection.py
Labels: bug

#250 DEV: Fix Flake8 Errors And Typos In `misc.py`
  README.md
  tests/test_utils.py
  tiatoolbox/utils/misc.py
  whitelist.txt
Labels: code readability

#263 DEV: Fix Flake8 Errors And Typos In `transforms.py`
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/utils/transforms.py
Labels: code readability

#261 BUG: Add User Warning For Missing SQLite Functions
  tests/test_annotation_stores.py
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
Labels: bug

#265 DEV: Update version numbers of dependent libraries
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.py
  tox.ini
Labels: dev tools

#272 REL: Release 1.0.1
  .deepsource.toml
  CITATION.cff
  HISTORY.md
  README.md
  examples/inference-pipelines/idars.ipynb
  examples/inference-pipelines/slide-graph.ipynb
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.cfg
  setup.py
  tests/models/test_abc.py
  tests/models/test_dataset.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_annotation_stores.py
  tests/test_exceptions.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/__init__.py
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/utils/__init__.py
  tiatoolbox/utils/env_detection.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
  tox.ini
  whitelist.txt
Labels: release
