Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-05, with the labels that each got.

#335 DOC: Add Metrics Tables To Documentation
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/idars.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
Labels: documentation

#320 EG: Add Benchmark Notebook For Annotations
  .pre-commit-config.yaml
  benchmarks/annotation_store.ipynb
  benchmarks/annotation_store_alloc.py
  requirements.conda.yml
  setup.cfg
  tests/test_annotation_stores.py
  tiatoolbox/annotation/storage.py
  whitelist.txt
Labels: documentation

#328 ADD: Add Support For Multiple Channel Images (HxWxC)
  tests/test_utils.py
  tiatoolbox/utils/transforms.py
Labels: enhancement

#273 ENH: Fix Bugs & Improve UNet Architecture
  .pre-commit-config.yaml
  tests/models/test_arch_unet.py
  tiatoolbox/models/architecture/unet.py
  whitelist.txt
Labels: bug, enhancement
