Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-10, with the labels that each got.

#484 DEV: Fix Circular import `wsireader`
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug

#465 NEW: Add DFBRegistration Function
  tests/test_wsi_registration.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: enhancement

#486 BUG: Read MPP Metadata From NGFF v0.4 Zattrs
  tests/test_wsireader.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: bug

#489 BUG: Read TIFF Resolution Tags As A Fraction
  tiatoolbox/wsicore/wsireader.py
Labels: bug

#445 ENH: Annotation Storage Additions For Visualization
  tests/test_annotation_stores.py
  tests/test_utils.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#488 NEW: Non-Rigid Registration Using SimpleITK
  requirements.txt
  tests/test_wsi_registration.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: enhancement

#485 [skip ci] DOC: DFBR Jupyter Notebook
  docs/images/wsi-registration.png
  examples/10-wsi_registration.ipynb
  examples/README.md
Labels: documentation

#431 BUG: Update HoVer-Net+ Post-processing
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
Labels: enhancement
