Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-09, with the labels that each got.

#439 DOC: Improve 07-advanced-modeling.ipynb
  examples/07-advanced-modeling.ipynb
  examples/inference-pipelines/idars.ipynb
Labels: documentation

#434 NEW: Add SCCNN Cell Detection Architecture
  docs/usage.rst
  tests/models/test_arch_micronet.py
  tests/models/test_arch_sccnn.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
  whitelist.txt
Labels: enhancement

#443 NEW: Add MapDe architecture.
  docs/usage.rst
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
Labels: enhancement

#456 DEV: Create pip Install From Git Workflow
  .github/workflows/pip-install.yml
Labels: dev tools, release

#421 DOC: JNB-RTD consistency for idars.ipynb
  examples/inference-pipelines/idars.ipynb
Labels: documentation

#432 DOC: JNB-RTD consistency for 05-patch-prediction.ipynb
  examples/05-patch-prediction.ipynb
Labels: documentation

#451 ENH: Add Min Mask Ratio Parameter in PatchExtractor
  tests/test_patch_extraction.py
  tiatoolbox/tools/patchextraction.py
Labels: enhancement

#425 DOC: JNB-RTD consistency for full-pipelines/slide-graph.ipynb
  examples/full-pipelines/slide-graph.ipynb
Labels: documentation

#429 DOC: JNB-RTD consistency for 01-wsi-reading.ipynb
  examples/01-wsi-reading.ipynb
Labels: documentation

#457 DOC: Change HTML Theme to furo
  docs/conf.py
  docs/index.rst
  docs/installation.rst
  docs/readme.md
  docs/readme.rst
  docs/requirements.txt
Labels: documentation

#469 [skip ci] DOC: Remove `nbgallery`
  README.md
  docs/_static/sg_gallery.css
  docs/conf.py
  docs/images/advanced-techniques.png
  docs/images/hovernet.png
  docs/images/hovernetplus.png
  docs/images/patch-extraction.png
  docs/images/patch-prediction.png
  docs/images/wsi-reading.png
  docs/notebooks.rst
  docs/requirements.txt
  examples/README.md
  tiatoolbox/models/architecture/__init__.py
Labels: documentation

#440 NEW: Feature Matching for Deep Feature Based Registration
  tests/test_wsi_registration.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: enhancement

#470 DEV: Add `docs/requirements.txt` to `requirements_dev.txt`
  .github/workflows/conda-env-create.yml
  requirements_dev.txt
Labels: dev tools, dependencies

#467 DEV: Use `requirements.txt` in `setup.py`
  MANIFEST.in
  requirements.txt
  setup.py
Labels: dependencies

#464 DEV: Add macOS To pip Install Workflow
  .github/workflows/pip-install.yml
  setup.py
Labels: dev tools

#480 [skip ci] DOC: Update citation in README.md and CITATION.cff
  CITATION.cff
  README.md
Labels: documentation
