Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-02, with the labels that each got.

#274 DEV: Update to latest `black` format
  README.md
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/wsicore/wsireader.py
  tox.ini
Labels: code readability

#268 DEV: Fix Flake8 Errors And Typos In `stainextract.py`
  tiatoolbox/tools/stainextract.py
  whitelist.txt
Labels: refactoring

#270 NEW: Add DICOM Read Support
  .pre-commit-config.yaml
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.py
  tests/test_wsireader.py
  tiatoolbox/data/__init__.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: enhancement, refactoring

#283 BUG: Fix Graph Functions
  tests/test_graph.py
  tiatoolbox/tools/graph.py
Labels: bug, refactoring

#280 ENH: Improve Error Messages
  tests/models/test_multi_task_segmentor.py
  tests/models/test_patch_predictor.py
  tests/test_exceptions.py
  tests/test_graph.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/dataset/abc.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/graph.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#281 DEV: Fix Flake8 Errors And Typos In `patchextraction.py`
  tests/test_patch_extraction.py
  tiatoolbox/tools/patchextraction.py
Labels: documentation, code readability

#292 BUG: Fix Travis Detection
  .travis.yml
  tests/test_utils.py
  tox.ini
Labels: bug, dev tools

#290 DEV: Create dependabot.yml
  .github/dependabot.yml
Labels: dev tools

#286 DOC: Update docs with Docker instructions
  docs/installation.rst
Labels: documentation

#300 DEV: Dependency upgrades
  requirements.dev.conda.yml
  requirements_dev.txt
  tox.ini
Labels: dependencies

#284 DEV: Update scikit-image Version
  requirements.conda.yml
  requirements.dev.conda.yml
  requirements.txt
  requirements.win64.conda.yml
  requirements_dev.txt
  setup.py
  tests/test_wsireader.py
Labels: bug, dev tools, release

#293 NEW: Add `micronet`
  docs/pretrained.rst
  docs/usage.rst
  tests/models/test_arch_micronet.py
  tests/models/test_hovernet.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/micronet.py
  whitelist.txt
Labels: enhancement
