Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2022-04, with the labels that each got.

#313 BUG: Fixed Performance Issue In semantic_segmentor.py
  tests/models/test_feature_extractor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/semantic_segmentor.py
Labels: bug

#332 DEV: Ignore `tmp_path` Paths For DeepSource
  setup.cfg
  tests/models/test_arch_micronet.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/test_annotation_stores.py
  tests/test_pyramid.py
  tests/test_slide_info.py
  tests/test_stainnorm.py
  tests/test_wsireader.py
  tiatoolbox/data/__init__.py
Labels: dev tools

#317 ENH: Add Better Support For Tiled TIFFs
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/utils/misc.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug, enhancement
