Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-12, with the labels that each got.

#753 :white_check_mark: Add `mypy` checks to `image.py`
  .github/workflows/mypy-type-check.yml
  tiatoolbox/typing.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/transforms.py
Labels: dev tools

#684 ✨ Add `bokeh` Visualization
  MANIFEST.in
  docs/images/dual_win.png
  docs/images/properties_window.png
  docs/images/type_select.png
  docs/images/vis_gland_cmap.png
  docs/images/vis_graph.png
  docs/images/visualize_interface.png
  docs/index.rst
  docs/installation.rst
  docs/visualization.rst
  requirements/requirements.txt
  tests/conftest.py
  tests/test_annotation_tilerendering.py
  tests/test_app_bokeh.py
  tests/test_json_config_bokeh.py
  tests/test_server_bokeh.py
  tests/test_tileserver.py
  tests/test_utils.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/cli/__init__.py
  tiatoolbox/cli/visualize.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/misc.py
  tiatoolbox/visualization/bokeh_app/__init__.py
  tiatoolbox/visualization/bokeh_app/app_hooks.py
  tiatoolbox/visualization/bokeh_app/main.py
  tiatoolbox/visualization/bokeh_app/templates/index.html
  tiatoolbox/visualization/tileserver.py
  tiatoolbox/visualization/tileserver_api.yml
  tiatoolbox/visualization/ui_utils.py
Labels: enhancement

#752 🩹 Fix `save_tiles`
  tiatoolbox/wsicore/wsireader.py
Labels: bug

#755 :white_check_mark: Add `mypy` checks to `visualization.py`
  .github/workflows/mypy-type-check.yml
  tests/test_wsireader.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
Labels: dev tools

#761 🔖 Release 1.5.0
  .github/workflows/docker-publish.yml
  AUTHORS.md
  CITATION.cff
  HISTORY.md
  pyproject.toml
  setup.py
  tiatoolbox/__init__.py
  tiatoolbox/annotation/storage.py
Labels: release

#764 🚑 Release 1.5.1
  .github/workflows/docker-publish.yml
  CITATION.cff
  HISTORY.md
  pyproject.toml
  setup.py
  tiatoolbox/__init__.py
Labels: release

#766 🚑 Release 1.5.1
  .github/workflows/docker-publish.yml
  CITATION.cff
  HISTORY.md
  pyproject.toml
  setup.py
  tiatoolbox/__init__.py
Labels: release
