Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-03, with the labels that each got.

#551 :pushpin: DEV: Pin Scikit-image < 0.20
  requirements.txt
Labels: dependencies

#552 🔖 REL: Release 1.3.3
  .github/workflows/docker-publish.yml
  CITATION.cff
  HISTORY.md
  requirements.txt
  setup.cfg
  setup.py
  tiatoolbox/__init__.py
Labels: release

#545 :arrow_up: DEP: Update matplotlib Based Code
  tests/test_annotation_tilerendering.py
  tests/test_visualization.py
  tiatoolbox/utils/visualization.py
Labels: dependencies

#554 🔖 REL: Release 1.3.3
  .github/workflows/docker-publish.yml
  CITATION.cff
  HISTORY.md
  setup.cfg
  setup.py
  tiatoolbox/__init__.py
Labels: release

#490 :rotating_light: DEV: Use logger Instead Of print (`save_tiles.py`)
  tests/test_exceptions.py
  tests/test_save_tiles.py
  tests/test_wsireader.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/save_tiles.py
  tiatoolbox/wsicore/__init__.py
  tiatoolbox/wsicore/save_tiles.py
  tiatoolbox/wsicore/wsireader.py
Labels: refactoring

#553 :arrow_up: DEV: Upgrade Scikit-image Dependency
  requirements.txt
  tests/models/test_arch_nuclick.py
  tiatoolbox/models/architecture/nuclick.py
Labels: dependencies

#546 :adhesive_bandage: ENH: Apply Stain Augmentation to Tissue Regions
  tiatoolbox/tools/stainaugment.py
Labels: enhancement

#562 🚨 DEV: Use logger Instead Of print (`slide_info.py`)
  tests/test_exceptions.py
  tests/test_slide_info.py
  tiatoolbox/cli/slide_info.py
  tiatoolbox/wsicore/__init__.py
  tiatoolbox/wsicore/slide_info.py
Labels: refactoring

#560 :art: ENH: Move `WSIReader` and `WSIMeta` import to top-level
  tests/test_wsimeta.py
  tests/test_wsireader.py
  tiatoolbox/wsicore/__init__.py
Labels: enhancement

#565 :memo: DOC: Improve Annotation Store Documentation + Fix Bug
  tests/test_annotation_stores.py
  tiatoolbox/annotation/storage.py
  whitelist.txt
Labels: documentation

#567 :memo: DOC: Improve Installation Instructions
  README.md
  docs/installation.rst
Labels: documentation

#568 🩹 BUG: Fix Parsing Missing Omero Version NGFF Metadata
  tests/test_wsireader.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: bug

#575 :wrench: Use `pyproject.toml` for `bdist_wheel` Configuration
  pyproject.toml
  setup.cfg
Labels: dev tools

#573 🔧 Use `pyproject.toml` for `pytest` Configuration
  pyproject.toml
Labels: dev tools

#572 :wrench: Use `pyproject.toml` for `isort` Configuration
  pyproject.toml
  setup.cfg
Labels: dev tools

#579 🔧 Use `pyproject.toml` for `pytest` Configuration
  pyproject.toml
  setup.cfg
Labels: dev tools

#580 🐛 Fix for Recent `wsidicom` Update
  tiatoolbox/wsicore/wsireader.py
Labels: bug
