Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-04, with the labels that each got.

#581 ➕ Add `joblib` As Dependency
  requirements.txt
Labels: dependencies

#585 :pushpin: Update `black` Version to `23.3.0`
  .pre-commit-config.yaml
  requirements.txt
  requirements_dev.txt
Labels: dependencies

#583 📌 Pin `pandas` Version to `>=2.0.0`
  requirements.txt
  tiatoolbox/annotation/storage.py
Labels: dependencies

#591 ✅ Add Tests For Lazy Import
  tests/test_init.py
Labels: dev tools

#590 🚨 Use `logger` Instead Of `warnings` for `pyramid.py` and `storage.py`
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_init.py
  tiatoolbox/__init__.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/tools/pyramid.py
Labels: enhancement

#586 🚨 Use `logger` Instead Of `warnings` for `utils` Package
  tests/test_annotation_tilerendering.py
  tests/test_utils.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/visualization.py
Labels: enhancement

#592 :page_facing_up: Update Documentation for License on Model Weights
  LICENSE
  README.md
  docs/pretrained.rst
Labels: documentation

#584 🚨 Use `logger` Instead Of `warnings` for `wsireader.py`
  tests/test_tiffreader.py
  tests/test_wsireader.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#519 🧑‍💻 Add Notebook URL Replacement Command
  .pre-commit-config.yaml
  Makefile
  pre-commit/notebook_check_ast.py
  pre-commit/notebook_markdown_format.py
  pre-commit/notebook_urls.py
Labels: dev tools

#563 :recycle: Move `requirements*.txt` to `requirements` Folder
  .deepsource.toml
  .github/workflows/conda-env-create.yml
  .github/workflows/pip-install.yml
  .github/workflows/python-package.yml
  .readthedocs.yml
  MANIFEST.in
  README.md
  docs/conf.py
  pre-commit/missing_imports.py
  pre-commit/requirements_consistency.py
  requirements/requirements.conda.yml
  requirements/requirements.dev.conda.yml
  requirements/requirements.txt
  requirements/requirements.win64.conda.yml
  requirements/requirements.win64.dev.conda.yml
  requirements/requirements_dev.txt
  setup.py
Labels: refactoring

#594 🐛 Fix `deepsource` Errors
  pre-commit/notebook_urls.py
  tests/models/test_patch_predictor.py
  tests/test_wsireader.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/tools/stainaugment.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug, dev tools
