Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-10, with the labels that each got.

#719 :arrow_up: Update `torch` Dependency
  requirements/requirements.txt
Labels: dependencies

#718 ❇️ Add Convert `patches` Output to `AnnotationStore`
  tests/test_utils.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#725 :hammer: Add `mypy` Checks to `exceptions.py`
  .github/workflows/mypy-type-check.yml
  requirements/requirements_dev.txt
  tiatoolbox/utils/exceptions.py
Labels: dev tools

#724 ❇️ Add Function to Save Engines Output in the `zarr` Format
  tests/test_utils.py
  tiatoolbox/utils/misc.py
Labels: dev tools

#635 :art: New `EngineABC` Design for `Patches`
  .gitignore
  tests/engines/_test_feature_extractor.py
  tests/engines/_test_multi_task_segmentor.py
  tests/engines/_test_nucleus_instance_segmentor.py
  tests/engines/_test_patch_predictor.py
  tests/engines/_test_semantic_segmentation.py
  tests/engines/test_engine_abc.py
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tests/models/test_arch_sccnn.py
  tests/models/test_arch_unet.py
  tests/models/test_arch_vanilla.py
  tests/models/test_hovernet.py
  tests/models/test_hovernetplus.py
  tests/models/test_models_abc.py
  tests/test_annotation_tilerendering.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/engine/__init__.py
  tiatoolbox/models/engine/engine_abc.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/models/models_abc.py
Labels: enhancement
