Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-06, with the labels that each got.

#616 ✨ File Magic Detection & NGFF SQLite3 Support
  tests/test_magic.py
  tests/test_wsireader.py
  tiatoolbox/utils/magic.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: enhancement

#621 :recycle: Replace deprecated input `pretrained` with `weights`
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: refactoring

#622 :wastebasket: Remove `shapely.speedups`
  tiatoolbox/annotation/storage.py
  tiatoolbox/utils/visualization.py
Labels: invalid
