Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-11, with the labels that each got.

#731 :hammer: Add `typing.py` and `env_detection.py` to `mypy` Type Check
  .github/workflows/mypy-type-check.yml
  pyproject.toml
  tiatoolbox/typing.py
  tiatoolbox/utils/env_detection.py
Labels: code readability

#733 ♻️ Update `model_to()` and `load_torch_model()` methods in `ModelABC`
  tests/models/test_abc.py
  tiatoolbox/models/models_abc.py
Labels: enhancement

#721 ✨ Add Support for `QuPath` Annotation Imports
  tests/test_annotation_stores.py
  tiatoolbox/annotation/storage.py
Labels: enhancement

#740 :hammer: Add `mypy` Checks
  .github/workflows/mypy-type-check.yml
  tests/test_utils.py
  tiatoolbox/typing.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
Labels: dev tools

#744 :hammer: Add `utils/misc.py` to mypy
  .github/workflows/mypy-type-check.yml
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
Labels: dev tools
