Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-05, with the labels that each got.

#597 🐛 Fix `MultiTaskSegmentor` Example
  tests/test_docs.py
  tiatoolbox/models/engine/multi_task_segmentor.py
Labels: documentation

#543 :arrow_up: Upgrade `numpy` Dependency
  requirements/requirements.txt
  tests/models/test_patch_predictor.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/utils/metrics.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/wsicore/wsireader.py
Labels: dependencies

#540 :sparkles: ENH: Add Neighbourhood Querying Support To `AnnotationStore`
  benchmarks/annotation_nquery.ipynb
  benchmarks/nquery-concept.svg
  docs/images/nquery-box-box.png
  docs/images/nquery-boxpoint-boxpoint.png
  docs/images/nquery-poly-poly.png
  tests/test_annotation_stores.py
  tests/test_dsl.py
  tiatoolbox/annotation/storage.py
  whitelist.txt
Labels: enhancement

#500 🐍 Update Supported Python Versions (add 3.11 )
  .github/workflows/pip-install.yml
  .github/workflows/python-package.yml
  requirements/requirements.conda.yml
  requirements/requirements.dev.conda.yml
  requirements/requirements.txt
  requirements/requirements.win64.conda.yml
  requirements/requirements.win64.dev.conda.yml
  setup.py
Labels: release, dependencies

#588 🚨 Use `logger` Instead Of `warnings` for `models` Package
  tests/models/test_arch_nuclick.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
Labels: enhancement

#587 🚨 Use `logger` Instead Of `warnings` for `wsi_registration.py`
  tests/test_wsi_registration.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: enhancement

#606 :recycle: High Level `misc` functions Import
  requirements/requirements.txt
  tests/models/test_arch_nuclick.py
  tests/models/test_dataset.py
  tests/models/test_hovernetplus.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_stainaugment.py
  tests/test_stainnorm.py
  tests/test_tileserver.py
  tests/test_utils.py
  tests/test_wsi_registration.py
  tests/test_wsireader.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/read_bounds.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/cli/slide_info.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/cli/stain_norm.py
  tiatoolbox/cli/tissue_mask.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/dataset/info.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/tissuemask.py
  tiatoolbox/utils/__init__.py
  tiatoolbox/wsicore/wsireader.py
Labels: refactoring

#613 ✏️ Update `README.md`
  README.md
Labels: documentation

#612 🐛 Fix Errors with `glymur` Update to `0.12.6`
  requirements/requirements.txt
Labels: dependencies

#598 :recycle: Refactor `Resolution` and `Units`
  examples/full-pipelines/slide-graph.ipynb
  examples/inference-pipelines/slide-graph.ipynb
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: refactoring

#607 :recycle: High Level `engines` Import
  tests/models/test_arch_micronet.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/models/__init__.py
Labels: refactoring
