Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-07, with the labels that each got.

#630 :test_tube: Improve `micronet` Tests
  tests/models/test_arch_micronet.py
Labels: dev tools

#631 :white_check_mark: Improve Tests for `save_tiles` to Reduce Runtime
  tests/conftest.py
  tests/test_save_tiles.py
Labels: dev tools

#638 :technologist: Use `poetry` for Version Updates
  CONTRIBUTING.rst
  pyproject.toml
  requirements/requirements_dev.txt
  setup.cfg
  tiatoolbox/__init__.py
Labels: dev tools

#629 :technologist: Reduce Test runtime for JP2
  tests/test_wsireader.py
Labels: dev tools

#513 🚨 Expand Tile Server API
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_tileserver.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/annotation/__init__.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/visualization/__init__.py
  tiatoolbox/visualization/tileserver.py
  tiatoolbox/visualization/tileserver_api.yml
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: enhancement

#623 :art: Add typehints for `env_detection.py` and `exceptions.py`
  tiatoolbox/utils/env_detection.py
  tiatoolbox/utils/exceptions.py
Labels: code readability

#624 :memo: Fix docstrings
  tiatoolbox/annotation/storage.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/models/models_abc.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/utils/magic.py
  tiatoolbox/utils/metrics.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: documentation

#643 :recycle: Small tests improvements
  tests/conftest.py
  tests/test_utils.py
  tiatoolbox/utils/env_detection.py
Labels: dev tools

#641 ✅ Reuse models and datasets in tests
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tests/models/test_arch_sccnn.py
  tests/models/test_arch_unet.py
  tests/models/test_dataset.py
  tests/models/test_hovernet.py
  tests/models/test_hovernetplus.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_utils.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/dataset/info.py
Labels: dev tools

#640 :white_check_mark: Upgrade remote sample fixtures
  requirements/requirements.txt
  tests/conftest.py
  tests/models/test_dataset.py
  tests/test_tiffreader.py
  tests/test_utils.py
  tests/test_wsireader.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/dataset/info.py
  tiatoolbox/utils/misc.py
Labels: dev tools

#647 :rotating_light: Fix Linter Errors
  pre-commit/notebook_markdown_format.py
  pre-commit/notebook_urls.py
  setup.py
  tests/conftest.py
  tests/models/test_abc.py
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tests/models/test_arch_sccnn.py
  tests/models/test_arch_unet.py
  tests/models/test_arch_utils.py
  tests/test_docs.py
  tests/test_magic.py
  tests/test_metrics.py
  tests/test_save_tiles.py
  tests/test_scale.py
  tests/test_slide_info.py
  tests/test_slide_thumbnail.py
  tests/test_stainaugment.py
  tests/test_stainnorm.py
  tests/test_tiffreader.py
  tests/test_tissuemask.py
  tests/test_wsimeta.py
  tiatoolbox/cli/__init__.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/read_bounds.py
  tiatoolbox/cli/save_tiles.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/cli/slide_info.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/models_abc.py
  tiatoolbox/typing.py
  tiatoolbox/utils/metrics.py
  tiatoolbox/wsicore/__init__.py
  tiatoolbox/wsicore/metadata/__init__.py
Labels: code readability

#648 :rotating_light: Fix Linter Error in `cli`, `annotation` and `visualization`
  tiatoolbox/annotation/dsl.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/show_wsi.py
  tiatoolbox/cli/stain_norm.py
  tiatoolbox/cli/tissue_mask.py
  tiatoolbox/visualization/tileserver.py
Labels: code readability

#649 🚨 Fix Linter Error in `tools`, `utils` and `pre-commit`
  benchmarks/annotation_store_alloc.py
  pre-commit/missing_imports.py
  pre-commit/notebook_check_ast.py
  pre-commit/requirements_consistency.py
  tests/test_exceptions.py
  tests/test_patch_extraction.py
  tests/test_utils.py
  tests/test_visualization.py
  tests/test_wsireader.py
  tiatoolbox/tools/graph.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/tools/stainaugment.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/tools/tissuemask.py
  tiatoolbox/utils/env_detection.py
  tiatoolbox/utils/exceptions.py
  tiatoolbox/utils/magic.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/wsireader.py
  whitelist.txt
Labels: code readability

#650 :rotating_light: Replace `flake8` with `ruff` with Base Settings
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  docs/conf.py
  pyproject.toml
  requirements/requirements.txt
  requirements/requirements_dev.txt
  setup.cfg
  tiatoolbox/__init__.py
Labels: code readability

#632 ✨ Feature: `wkb` Decoding via `numpy`
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_visualization.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/visualization.py
  whitelist.txt
Labels: enhancement

#652 🚨 Add `bugbear`. `pep8-naming`, `flake8-commas`, `flake8-print`, `mccabe`, `pycodestyle-Error` and `pyupgrade` Checks
  pyproject.toml
  tests/models/test_arch_vanilla.py
  tests/models/test_dataset.py
  tests/models/test_hovernet.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_dsl.py
  tests/test_exceptions.py
  tests/test_graph.py
  tests/test_tileserver.py
  tests/test_utils.py
  tests/test_visualization.py
  tests/test_wsi_registration.py
  tests/test_wsireader.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/idars.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/dataset/info.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: code readability

#653 🚨 Add `Perflint`, `flake8-simplify`, `flake8-raise`, `flake8-implicit-str-concat`, `flake8-fixme`, `pandas-vet`
  benchmarks/annotation_store_alloc.py
  pyproject.toml
  tests/models/test_dataset.py
  tests/models/test_feature_extractor.py
  tests/models/test_hovernet.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_dsl.py
  tests/test_exceptions.py
  tests/test_graph.py
  tests/test_init.py
  tests/test_meta_ngff_dataclasses.py
  tests/test_pyramid.py
  tests/test_tileserver.py
  tests/test_wsi_registration.py
  tests/test_wsireader.py
  tiatoolbox/__main__.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/dataset/info.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/graph.py
  tiatoolbox/utils/env_detection.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/wsicore/metadata/ngff.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: code readability

#625 ✨ Use `ruff` for Linting
  pyproject.toml
  tests/test_data.py
  tests/test_wsireader.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/wsicore/wsireader.py
Labels: dev tools

#618 :recycle: Refactor base code from `IOSegmentorConfig` to `ModelIOConfigABC`
  .github/workflows/python-package.yml
  tests/engines/__init__.py
  tests/engines/test_ioconfig.py
  tests/models/test_feature_extractor.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/data/pretrained_model.yaml
  tiatoolbox/models/__init__.py
  tiatoolbox/models/engine/engine_abc.py
  tiatoolbox/models/engine/io_config.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  whitelist.txt
Labels: enhancement

#637 :recycle: Move Dataset Classes to `dataset_abc.py`
  tests/models/test_dataset.py
  tiatoolbox/models/__init__.py
  tiatoolbox/models/dataset/__init__.py
  tiatoolbox/models/dataset/classification.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/engine/__init__.py
  tiatoolbox/models/engine/io_config.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
Labels: code readability
