Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2023-08, with the labels that each got.

#644 💚 Add CI Cache
  .github/workflows/python-package.yml
Labels: dev tools

#678 :rotating_light: `ruff` tiatoolbox root
  tests/test_init.py
  tiatoolbox/__init__.py
Labels: code readability

#676 🚨 Add `ruff` Checks to All Jupyter Notebooks
  .pre-commit-config.yaml
  benchmarks/annotation_nquery.ipynb
  benchmarks/annotation_store.ipynb
  benchmarks/annotation_store_alloc.py
  pyproject.toml
Labels: code readability

#683 :rotating_light: Fix `ANN201` Errors in `tests`
  docs/conf.py
  pre-commit/requirements_consistency.py
  tests/conftest.py
  tests/models/test_abc.py
  tests/models/test_arch_idars.py
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tests/models/test_arch_sccnn.py
  tests/models/test_arch_unet.py
  tests/models/test_arch_utils.py
  tests/models/test_arch_vanilla.py
  tests/models/test_dataset.py
  tests/models/test_feature_extractor.py
  tests/models/test_hovernet.py
  tests/models/test_hovernetplus.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_data.py
  tests/test_docs.py
  tests/test_dsl.py
  tests/test_exceptions.py
  tests/test_graph.py
  tests/test_init.py
  tests/test_magic.py
  tests/test_metrics.py
  tests/test_patch_extraction.py
  tests/test_pyramid.py
  tests/test_save_tiles.py
  tests/test_scale.py
  tests/test_slide_info.py
  tests/test_slide_thumbnail.py
  tests/test_stainaugment.py
  tests/test_stainnorm.py
  tests/test_tiatoolbox.py
  tests/test_tiffreader.py
  tests/test_tileserver.py
  tests/test_tissuemask.py
  tests/test_utils.py
  tests/test_visualization.py
  tests/test_wsi_registration.py
  tests/test_wsimeta.py
  tests/test_wsireader.py
  tiatoolbox/cli/read_bounds.py
  tiatoolbox/cli/slide_thumbnail.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/utils/magic.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug, code readability

#690 :arrow_up: Upgrade `ruff` to `0.0.284`
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  requirements/requirements_dev.txt
Labels: code readability

#646 :adhesive_bandage: Add `imwrite` Check
  tests/test_utils.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#685 🚨 Fix Linter Errors in `utils`
  tiatoolbox/utils/env_detection.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/metrics.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
Labels: code readability

#693 🐛 Fix `prealignment` Function
  tiatoolbox/tools/registration/wsi_registration.py
Labels: bug

#673 :thread: Safer downloads
  tiatoolbox/utils/misc.py
Labels: enhancement

#696 :rotating_light: Add `flake8-annotations` to `Visualization`
  tiatoolbox/visualization/tileserver.py
Labels: code readability

#639 ✨ Extend Annotation to Support Init from WKB
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_enums.py
  tests/test_visualization.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/enums.py
  tiatoolbox/typing.py
  tiatoolbox/utils/visualization.py
Labels: enhancement

#698 :arrow_up: Upgrade `ruff` to `0.0.285`
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  requirements/requirements_dev.txt
  tiatoolbox/models/engine/multi_task_segmentor.py
Labels: dependencies

#700 :rotating_light: Fix `flake8-annotations` for `wsicore`
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: code readability

#701 :rotating_light: Add `flake8-annotations` Checks for `engine`
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/tools/patchextraction.py
Labels: code readability

#671 💚 Parallel tests
  Makefile
  requirements/requirements_dev.txt
  tests/conftest.py
  tests/models/test_hovernetplus.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_init.py
  tests/test_utils.py
  tests/test_wsireader.py
Labels: dev tools

#697 📝 Fix Docstrings in `PatchExtractor`
  tiatoolbox/tools/patchextraction.py
Labels: documentation

#704 :arrow_up: Upgrade `ruff` to version `0.0.286`
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  requirements/requirements_dev.txt
Labels: dependencies

#705 :recycle: Refactor Minor Changes to Keep #635 Clean
  pyproject.toml
  tests/engines/_test_feature_extractor.py
  tests/engines/_test_multi_task_segmentor.py
  tests/engines/_test_nucleus_instance_segmentor.py
  tests/engines/_test_patch_predictor.py
  tests/engines/_test_semantic_segmentation.py
  tests/models/test_abc.py
  tests/models/test_arch_vanilla.py
  tests/test_utils.py
  tests/test_wsimeta.py
  tiatoolbox/models/__init__.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/models/models_abc.py
  tiatoolbox/utils/misc.py
Labels: refactoring

#706 🚨 Add `flake8-annotations` to `tests\models` and `tests\"root"`
  pre-commit/missing_imports.py
  pre-commit/requirements_consistency.py
  tests/conftest.py
  tests/models/test_abc.py
  tests/models/test_dataset.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
Labels: code readability

#707 🚨 Add `flake8-annotations` to All Except `tiatoolbox/annotations`
  tests/test_docs.py
  tests/test_graph.py
  tests/test_patch_extraction.py
  tests/test_pyramid.py
  tests/test_save_tiles.py
  tests/test_slide_info.py
  tests/test_slide_thumbnail.py
  tests/test_stainaugment.py
  tests/test_stainnorm.py
  tests/test_tiffreader.py
  tests/test_tileserver.py
  tests/test_tissuemask.py
  tests/test_utils.py
  tests/test_wsi_registration.py
  tests/test_wsireader.py
  tiatoolbox/enums.py
Labels: code readability
