Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-11, with the labels that each got.

#871 🐛 Add Warning for `VahadaneExtractor` Algorithm Instability
  tests/test_stainnorm.py
  tiatoolbox/tools/stainextract.py
Labels: documentation

#716 ⚡️Add `torch.compile` Functionality
  .github/workflows/python-package.yml
  tests/conftest.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_utils.py
  tests/test_wsi_registration.py
  tiatoolbox/__init__.py
  tiatoolbox/models/architecture/__init__.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/engine/multi_task_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/models/models_abc.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/utils/__init__.py
Labels: enhancement

#865 ✨ Add `PatchPredictor` Engine
  tests/engines/test_engine_abc.py
  tests/engines/test_patch_predictor.py
  tests/models/test_models_abc.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/engine/engine_abc.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#882 ♻️ Update Changes from New Engine Design
  .gitignore
  tests/models/test_abc.py
  tests/models/test_arch_mapde.py
  tests/models/test_arch_micronet.py
  tests/models/test_arch_nuclick.py
  tests/models/test_arch_sccnn.py
  tests/models/test_arch_unet.py
  tests/models/test_arch_vanilla.py
  tests/models/test_feature_extractor.py
  tests/models/test_hovernet.py
  tests/models/test_hovernetplus.py
  tests/models/test_multi_task_segmentor.py
  tests/models/test_nucleus_instance_segmentor.py
  tests/models/test_patch_predictor.py
  tests/models/test_semantic_segmentation.py
  tests/test_annotation_stores.py
  tests/test_annotation_tilerendering.py
  tests/test_init.py
  tests/test_utils.py
  tests/test_wsimeta.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/models/architecture/hovernet.py
  tiatoolbox/models/architecture/hovernetplus.py
  tiatoolbox/models/architecture/mapde.py
  tiatoolbox/models/architecture/micronet.py
  tiatoolbox/models/architecture/nuclick.py
  tiatoolbox/models/architecture/sccnn.py
  tiatoolbox/models/architecture/unet.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/engine/nucleus_instance_segmentor.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/models/engine/semantic_segmentor.py
  tiatoolbox/models/models_abc.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/visualization.py
  tiatoolbox/visualization/bokeh_app/main.py
  whitelist.txt
Labels: enhancement

#888 :technologist: Add Warning for `torch.compile` on Windows.
  tiatoolbox/models/architecture/utils.py
Labels: bug
