Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-08, with the labels that each got.

#842 🧑‍💻 Fix `mypy` Type Error in `tiatoolbox/tools`
  tiatoolbox/tools/graph.py
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/tools/stainaugment.py
  tiatoolbox/tools/tissuemask.py
  tiatoolbox/utils/misc.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug, code readability, dev tools

#845 :bug: Fix `test_dsl` for `pytest`>=8.3.0
  .github/workflows/python-package.yml
  requirements/requirements_dev.txt
  tests/test_dsl.py
Labels: bug, dependencies

#850 🐛 Fix Immutable Output from `WSIReader`
  tiatoolbox/utils/transforms.py
Labels: bug, enhancement
