Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-09, with the labels that each got.

#861 :heavy_minus_sign: Remove `jinja2` dependency
  requirements/requirements_dev.txt
Labels: dependencies

#862 :hammer: Update test build for `Ubuntu-24.04`
  .github/workflows/mypy-type-check.yml
  .github/workflows/pip-install.yml
  .github/workflows/python-package.yml
  .readthedocs.yml
  requirements/requirements.txt
Labels: dev tools

#854 📝 Add `WSIReader` Type Annotation to `input_img` for `PatchExtrator`
  tiatoolbox/tools/patchextraction.py
Labels: documentation

#783 🧑‍💻 Define `PatchPredictor`
  tests/engines/test_engine_abc.py
  tests/engines/test_patch_predictor.py
  tests/models/test_dataset.py
  tests/test_annotation_stores.py
  tests/test_init.py
  tests/test_utils.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/models/architecture/vanilla.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/models/engine/engine_abc.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#864 :bug: Fix `mypy` Type Checks for `cli/common.py`
  tiatoolbox/cli/common.py
Labels: bug
