Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-02, with the labels that each got.

#779 🐛Fix `test` in `test_annotation_stores.py`
  tests/test_annotation_stores.py
  tests/test_stainnorm.py
Labels: bug

#772 🐛 Fix `json_extract` Construction
  tests/test_dsl.py
  tiatoolbox/annotation/dsl.py
Labels: bug

#782 :hammer: `mypy` type check `tools/`
  .github/workflows/mypy-type-check.yml
  tiatoolbox/tools/graph.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/tissuemask.py
  tiatoolbox/utils/visualization.py
Labels: refactoring

#786 :pushpin: Update minimum Python version to `3.9`
  .github/workflows/docker-publish.yml
  .github/workflows/mypy-type-check.yml
  .github/workflows/pip-install.yml
  .github/workflows/python-package.yml
  README.md
  benchmarks/annotation_store.ipynb
  benchmarks/annotation_store_alloc.py
  docker/3.11/Debian/Dockerfile
  docker/3.11/Ubuntu/Dockerfile
  docker/3.12/Debian/Dockerfile
  docker/3.12/Ubuntu/Dockerfile
  docs/installation.rst
  examples/full-pipelines/slide-graph.ipynb
  pyproject.toml
  requirements/requirements.conda.yml
  requirements/requirements.dev.conda.yml
  requirements/requirements.win64.conda.yml
  requirements/requirements.win64.dev.conda.yml
  setup.py
  tests/test_annotation_stores.py
  tests/test_app_bokeh.py
  tests/test_docs.py
  tests/test_dsl.py
  tests/test_wsireader.py
  tiatoolbox/__init__.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/cli/visualize.py
  tiatoolbox/data/__init__.py
  tiatoolbox/models/dataset/dataset_abc.py
  tiatoolbox/tools/pyramid.py
  tiatoolbox/tools/stainextract.py
  tiatoolbox/typing.py
  tiatoolbox/wsicore/wsimeta.py
  tiatoolbox/wsicore/wsireader.py
Labels: dependencies

#785 📌 Update `wsidicom` dependency
  requirements/requirements.txt
Labels: dependencies

#742 :children_crossing: Handle Multidimensional `Features` in `WSIReader`
  tests/test_wsireader.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement
