Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-06, with the labels that each got.

#821 :pushpin: Update `ruff` version.
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  requirements/requirements_dev.txt
Labels: dependencies

#806 Add `mypy` type check to `annotation/`
  .github/workflows/mypy-type-check.yml
  .gitignore
  tests/test_annotation_stores.py
  tests/test_stainnorm.py
  tests/test_utils.py
  tiatoolbox/annotation/dsl.py
  tiatoolbox/annotation/storage.py
  tiatoolbox/tools/stainnorm.py
  tiatoolbox/typing.py
  tiatoolbox/utils/image.py
  tiatoolbox/utils/misc.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
Labels: code readability

#800 ⚡️Refine `torch.compile` and Add to WSI Registration
  tests/models/test_patch_predictor.py
  tests/test_utils.py
  tests/test_wsi_registration.py
  tiatoolbox/__init__.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/engine/patch_predictor.py
  tiatoolbox/tools/registration/wsi_registration.py
Labels: enhancement
