Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-07, with the labels that each got.

#777 🐛 Fix `TIFFWSIReader` `read_bound`
  tests/conftest.py
  tests/test_tiffreader.py
  tests/test_wsireader.py
  tiatoolbox/data/remote_samples.yaml
  tiatoolbox/visualization/bokeh_app/main.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug, help wanted

#832 📌 Fix Compatibility with `bokeh` Version `3.5.0`
  requirements/requirements.txt
  tiatoolbox/visualization/bokeh_app/main.py
Labels: bug, dependencies

#831 🐛 Add `mypy` Type Check `tools/wsi_registration.py`
  tiatoolbox/tools/registration/wsi_registration.py
Labels: bug, code readability, dev tools
