Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2024-03, with the labels that each got.

#795 :children_crossing: Refactor `cli.visualize` to Improve `cli` Response
  tiatoolbox/__init__.py
  tiatoolbox/cli/visualize.py
Labels: enhancement

#796 :alien: Change `size` to `radius` for `bokeh 3.4` Compatibility
  tests/test_app_bokeh.py
  tiatoolbox/visualization/bokeh_app/main.py
Labels: bug, dependencies

#799 :pushpin: Fix `docs/requirements.txt` for `sphinx-design`
  docs/requirements.txt
Labels: dependencies

#801 Add `mypy` Type Check to `wsi_registration.py`
  .github/workflows/mypy-type-check.yml
  tiatoolbox/tools/registration/wsi_registration.py
Labels: code readability
