Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2025-05, with the labels that each got.

#931 🔧 `mypy` type check `tools/` and `utils/`
  tiatoolbox/tools/patchextraction.py
  tiatoolbox/tools/registration/wsi_registration.py
  tiatoolbox/utils/transforms.py
  tiatoolbox/utils/visualization.py
Labels: dev tools

#929 ✨ Add Feature to Write Model Probabilities as `ome.tiff` for Overlay
  tests/test_utils.py
  tiatoolbox/utils/misc.py
Labels: enhancement

#927 🐛 Fix Consecutive Annotations Load Bug
  tiatoolbox/visualization/tileserver.py
Labels: bug

#936 :pushpin: Setup to Install `openslide-binaries` using `pip`
  .github/workflows/pip-install.yml
  .github/workflows/python-package.yml
  docs/installation.rst
  requirements/requirements.txt
Labels: enhancement, dev tools, dependencies

#937 :pushpin: Pin `tifffile<=2025.5.10`
  requirements/requirements.txt
Labels: dependencies

#934 🐛 Fix DICOM Reading (Issue #933)
  tests/conftest.py
  tests/test_wsireader.py
  tiatoolbox/visualization/bokeh_app/main.py
  tiatoolbox/wsicore/wsireader.py
Labels: bug
