Repository TissueImageAnalytics/tiatoolbox, pull requests merged in 2025-03, with the labels that each got.

#914 :bug: Fix `MapDe` `dist_filter` Shape
  tests/models/test_arch_mapde.py
  tiatoolbox/models/architecture/mapde.py
Labels: bug

#897 Add FsspecJsonWSIReader class.
  requirements/requirements.txt
  tests/test_wsireader.py
  tiatoolbox/utils/tiff_to_fsspec.py
  tiatoolbox/wsicore/wsireader.py
Labels: enhancement

#906 ✨ Support for Additional Foundation Models
  tiatoolbox/models/architecture/vanilla.py
Labels: enhancement

#917 :recycle: Use `input_resolutions` instead of `resolution` in Engine Params
  tests/engines/test_engine_abc.py
  tests/engines/test_patch_predictor.py
  tiatoolbox/cli/common.py
  tiatoolbox/cli/nucleus_instance_segment.py
  tiatoolbox/cli/patch_predictor.py
  tiatoolbox/cli/semantic_segment.py
  tiatoolbox/models/architecture/utils.py
  tiatoolbox/models/engine/engine_abc.py
  tiatoolbox/models/engine/io_config.py
  tiatoolbox/models/engine/patch_predictor.py
Labels: refactoring
